version: '3.8'

services:
  # PostgreSQL Database (Latest Stable Version)
  postgres-user:
    image: postgres:16
    container_name: postgres-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-network

  # Hazelcast (Latest Stable Version)
  hazelcast-user:
    image: hazelcast/hazelcast:5.3.5
    container_name: hazelcast-user
    ports:
      - "5701:5701"
    environment:
      HZ_NETWORK_PORT: 5701
      HZ_CLUSTER_NAME: dev
    networks:
      - user-network

  # Spring Boot Application
  user-service:
    image: user-service:latest
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_HAZELCAST_NETWORK_MEMBERS: hazelcast:5701
      JWT_SECRET_KEY: 5PLwtPwpfCqxNQQmpwp2NBoRFru5C1b1taijGkWuSw5kGd6gbgcVj7b7e0CPJ1UQBRK2t/+qChLXRSaf/l0Ulg==
    depends_on:
      - postgres-user
      - hazelcast-user
    networks:
      - app-network
      - user-network

volumes:
  postgres_data:
networks:
  app-network:
    external: true
  user-network:
    driver: bridge